apiVersion: v1
kind: Pod
metadata:
  name: nopcommerce
spec:
  initContainers:
    - name: precondition1
      image: alpine
      args:
        - sleep
        - 60s
    - name: precondition2
      image: httpd
      args:
        - sleep
        - 120s
  containers:
    - name: nopcontainer
      image: siadevops/nopcoommerce:1.0
      ports:
        - containerPort: 5000
          protocol: TCP
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
