apiVersion: v1
kind: Pod
metadata:
  name: postgressdb
spec:
  containers:
    - name: postgressdbcontainer
      image: postgres:16
      env:
        - name: POSTGRES_PASSWORD
          value: sxz979
        - name: POSTGRES_DB
          value: nopdb
        - name: POSTGRES_USER 
          value: shahinur
      ports:
        - containerPort: 5432
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"