apiVersion: v1
kind: Pod
metadata:
    name: experiment
spec:
  containers:
    - image: nginx
      imagePullPolicy: Always
      name: nginxdemo
      ports:
        - containerPort: 80
          protocol: TCP
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"