apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts
  labels:
    app: nginx-sts
spec:
  minReadySeconds: 10
  ordinals:
    start: 100
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  serviceName: nginx-svc
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-sts-container
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/logs
              name: sts-volume
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: sts-volume
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: managed-csi
        resources:
          requests:
            storage: 1Gi
              
