apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend-rs
  labels:
    app: fe
spec:
  minReadySeconds: 10
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - fe
      - key: env
        operator: In
        values:
          - dev
  template:
    metadata:
      labels:
        app: fe
        env: dev
    spec:
      containers:
        - name: fe-nop
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
          livenessProbe:
            failureThreshold: 2
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            httpGet:
              path: /
              port: 80
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 2
            httpGet:
              path: /
              port: 80
          startupProbe:
            failureThreshold: 2
            initialDelaySeconds: 3
            periodSeconds: 30
            successThreshold: 1
            httpGet:
              path: /
              port: 80

            