apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  minReadySeconds: 1
  replicas: 2
  selector:
    matchLabels:
      app: travel
  template:
    metadata:
      labels:
        app: travel
    spec:
      containers:
        - name: nginx-container
          image: siadevops/htmldemo:1.0
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 80
              protocol: TCP
          