apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
spec:
  minReadySeconds: 23
  replicas: 1
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      labels:
        app: spc
    spec:
      containers:
        - name: spc-container
          image: siadevops/springpetclinic:1.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 30
            successThreshold: 1
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 30
            successThreshold: 1
          startupProbe:
            failureThreshold: 2
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 30
            successThreshold: 1
            
  
