apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: LoadBalancer
  ports:
    - name: nginx-svc-port
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: htmldemo