apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset
spec:
  minReadySeconds: 3
  replicas: 2
  selector:
    matchLabels:
      app: nop
      env: dev
  template:
    metadata:
      labels:
        app: nop
        env: dev
    spec:
      containers:
        - name: noprs
          image: siadevops/nopcoommerce:1.0
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"