apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-rs
  labels:
    app: be
spec:
  minReadySeconds: 2
  replicas: 2
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - be
      - key: env
        operator: In
        values:
          - dev
  template:
    metadata:
      labels:
        app: be
        env: dev
    spec:
      containers:
        - name: be-nop
          image: siadevops/nopcoommerce:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"