apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemonset
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
        - name: fluentd
          image: fluent/fluentd:v1.3-debian-1
          ports:
          - containerPort: 24224
            protocol: TCP
          - containerPort: 24224
            protocol: UDP
