apiVersion: v1
kind: Pod
metadata:
  name: config-demo
spec:
  containers:
    - name: config-container
      image: alpine
      args:
        - sleep
        - 1d
      envFrom:
        - configMapRef:
            name: sql-cm
      resources:
        limits:
          cpu: 500m
          memory: 512Mi