apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-config-container
      image: mysql:9
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - mountPath: /config
          name: configvolume 
  volumes:
    - configMap:
        name: sql-cm
      name: configvolume