apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: alpine
      args:
        - sleep
        - 1d
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
      volumeMounts:
        - mountPath: /config
          name: configvolume
  volumes:
    - name: configvolume
      configMap:
        name: sql-cm

      
       