apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod2
spec:
  containers:
    - name: mysql-config-container
      image: mysql:9
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
      env:
        - name: MYSQL_MAIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: sql-cm
        - name: MYSQL_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: sql-cm
      envFrom:
        - configMapRef:
            name: sql-cm
          
            