apiVersion: v1
kind: Pod
metadata:
  name: config-test
spec:
  containers:
    - name: config-container
      image: alpine
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
      args:
        - sleep
        - 1d
      env:
        - name: TEST_DATA-1
          valueFrom:
            configMapKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: sql-cm
      envFrom:
        - configMapRef:
            name: sql-cm
